config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount Decidim::Core::Engine => "/"
end

app/helpers/decidim/proposals/proposals_helper.rb
# frozen_string_literal: true

#   TODO:  this modifies entire file but only needs the function proposal_has_costs modified. refactor to only modify that funciton
module Decidim
  module Proposals
    # Simple helpers to handle markup variations for proposals
    module ProposalsHelper
      def proposal_reason_callout_announcement
        {
          title: proposal_reason_callout_title,
          body: decidim_sanitize(translated_attribute(@proposal.answer))
        }
      end

      def proposal_reason_callout_class
        case @proposal.state
        when "accepted"
          "success"
        when "evaluating"
          "warning"
        when "rejected"
          "alert"
        else
          ""
        end
      end

      def proposal_reason_callout_title
        i18n_key = case @proposal.state
                   when "evaluating"
                     "proposal_in_evaluation_reason"
                   else
                     "proposal_#{@proposal.state}_reason"
        end

        t(i18n_key, scope: "decidim.proposals.proposals.show")
      end

      def filter_proposals_state_values
        Decidim::CheckBoxesTreeHelper::TreeNode.new(
          Decidim::CheckBoxesTreeHelper::TreePoint.new("", t("decidim.proposals.application_helper.filter_state_values.all")),
          [
            Decidim::CheckBoxesTreeHelper::TreePoint.new("accepted", t("decidim.proposals.application_helper.filter_state_values.accepted")),
            Decidim::CheckBoxesTreeHelper::TreePoint.new("evaluating", t("decidim.proposals.application_helper.filter_state_values.evaluating")),
            Decidim::CheckBoxesTreeHelper::TreePoint.new("state_not_published", t("decidim.proposals.application_helper.filter_state_values.not_answered")),
            Decidim::CheckBoxesTreeHelper::TreePoint.new("rejected", t("decidim.proposals.application_helper.filter_state_values.rejected"))
          ]
        )
      end

      def proposal_has_costs?
        @proposal.cost.present? &&
          translated_attribute(@proposal.cost_report).present?
      end

      def resource_version(resource, options = {})
        return unless resource.respond_to?(:amendable?) && resource.amendable?

        super
      end
    end
  end
end

app/helpers/proposal_helper.rb
module ProposalHelper
  PROPOSALS_COMPONENT_SCOPE_VOTE_MESSAGE_KEY = {
    "DISTRITOS" => "decidim.proposals.proposals.voting_rules.proposal_scope.district",
    "SECTORES" => "decidim.proposals.proposals.voting_rules.proposal_scope.sector"
  }

  PROPOSALS_COMPONENT_SCOPE_CREATE_MESSAGE_KEY = {
    "DISTRITOS" => "decidim.proposals.proposals.create_proposal_rules.proposal_scope.district",
    "SECTORES" => "decidim.proposals.proposals.create_proposal_rules.proposal_scope.sector"
  }

  USER_SCOPE_METADATA_KEY = {
    "DISTRITOS" => "district_code",
    "SECTORES" => "sector_code"
  }

  def user_can_vote_district_proposal?(user, proposal)
    authorization = user_authorization(user)
    return false unless authorization && proposal.scope

    proposal.scope.code == authorization.metadata["district_code"]
  end

  def user_can_vote_sector_proposal?(user, proposal)
    authorization = user_authorization(user)
    return false unless authorization && proposal.scope

    proposal.scope.code == authorization.metadata["sector_code"]
  end

  def get_proposals_component_scope_vote_message_key(component_settings)
    component_scope = Decidim::Scope.find component_settings.scope_id
    PROPOSALS_COMPONENT_SCOPE_VOTE_MESSAGE_KEY[component_scope.code]
  end

  def get_proposals_component_scope_create_message_key(component_settings)
    component_scope = Decidim::Scope.find component_settings.scope_id
    PROPOSALS_COMPONENT_SCOPE_CREATE_MESSAGE_KEY[component_scope.code]
  end

  def is_component_scope_district?(component)
    Decidim::Scope.find(component.settings.scope_id).code == "DISTRITOS"
  end

  def is_component_scope_sector?(component)
    Decidim::Scope.find(component.settings.scope_id).code == "SECTORES"
  end

  def user_scope_name(user, component_settings)
    authorization = user_authorization(user)

    return "" unless authorization
    component_scope = Decidim::Scope.find component_settings.scope_id
    Decidim::Scope.find_by(code: authorization.metadata[USER_SCOPE_METADATA_KEY[component_scope.code]]).name
  end

  def user_authorization(user)
    ine_authorization = ::Decidim::Authorization.where
      .not(granted_at: nil)
      .find_by(user: user, name: "ine")

    managed_user_authorization = ::Decidim::Authorization.where
      .not(granted_at: nil)
      .find_by(user: user, name: "managed_user_authorization_handler")

    ine_authorization || managed_user_authorization
  end

  def user_has_monterrey_authorization?(user)
    return false unless user_authorization(user)
    true
  end

  def remaining_proposals_count_for(user)
    return 0 unless proposal_limit_enabled?

    proposals_count = Decidim::Proposals::Proposal.where(component: current_component)
      .where.not(published_at: nil)
      .joins(:coauthorships)
      .where(decidim_coauthorships: {
        decidim_author_type: ["Decidim::UserBaseEntity"],
        decidim_author_id: user.id
      })
      .except_withdrawn
      .to_a
      .size

    component_settings.proposal_limit - proposals_count
  end
end

app/views/decidim/proposals/proposals/_create_proposal_rules.erb
<div class="row column voting-rules">
  <div class="callout secondary">
    <div class="row">
      <div class="columns medium-8 large-9">
        <h3 class="heading3"><%= t(".title") %></h3>
        <ul>
          <% if proposal_limit_enabled? %>
            <li><%= t(".proposal_limit.description", limit: proposal_limit) %></li>
          <% end %>
          <% if current_user && user_has_monterrey_authorization?(current_user) && component_settings.scopes_enabled %>
            <li><%= raw t(get_proposals_component_scope_create_message_key(component_settings), scope_name: user_scope_name(current_user, component_settings)[I18n.locale.to_s]) %></li>
          <% end %>
        </ul>
      </div>
      <% if current_user && proposal_limit_enabled? %>
          <div class="columns medium-4 large-3">
            <div class="card card--nomargin text-center remaining-votes-counter">
              <div class="card__content">
                <span class="definition-data__title"><%= t(".proposal_limit.left", limit: proposal_limit) %></span>
                <span id="remaining-votes-count" class="extra__suport-number">
                  <%= remaining_proposals_count_for(current_user) %>
                </span>
                <span class="extra__suport-text"><%= t(".proposal_limit.proposals") %></span>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/decidim/proposals/proposals/_edit_form_fields.html.erb
<%= form_required_explanation %>

<div class="field hashtags__container">
  <%= form.text_field :title, class: "js-hashtags", value: form_presenter.title %>
</div>

<div class="field hashtags__container">
  <%= text_editor_for_proposal_body(form) %>
</div>

<% if @form.component_automatic_hashtags.any? %>
  <div class="field">
    <%= form.label :automatic_hashtags %>
    <div class="checkboxes hashtags">
      <% @form.component_automatic_hashtags.each do |hashtag| %>
        <label>
          <%= check_box_tag "", "", { checked: true }, { disabled: true } %>#<%= hashtag %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

<% if @form.component_suggested_hashtags.any? %>
  <div class="field">
    <%= form.label :suggested_hashtags, nil, for: nil %>
    <div class="checkboxes hashtags">
      <%= form.collection_check_boxes :suggested_hashtags, @form.component_suggested_hashtags.map { |hashtag| [hashtag.downcase, "##{hashtag}"] }, :first, :last do |option|
        option.label { option.check_box(checked: @form.suggested_hashtag_checked?(option.value)) + option.text }
      end %>
    </div>
  </div>
<% end %>

<% if @form.geocoding_enabled? %>
  <div class="field">
    <%= form.check_box :has_address, checked: form_has_address? %>
  </div>

  <div class="field" id="address_input">
    <%= form.geocoding_field :address, placeholder: t("decidim.proposals.proposals.placeholder.address") %>
    <div class="map" id="address_map">
      <%= render partial: "dynamic_map_instructions" %>
      <%= dynamic_map_for proposal_preview_data_for_map(@proposal) %>
    </div>
  </div>
<% end %>

<% if @form.categories&.any? %>
  <div class="field">
    <%= form.categories_select :category_id, @form.categories, include_blank: t("decidim.proposals.proposals.edit.select_a_category") %>
  </div>
<% end %>

<% unless Rails.env.production? %>
  <!--
    <% if current_component.has_subscopes? %>
      <div class="field">
        <%= scopes_picker_field form, :scope_id, root: current_component.scope %>
      </div>
    <% end %>
  -->
<% end %>
<% if current_organization.user_groups_enabled? && Decidim::UserGroups::ManageableUserGroups.for(current_user).verified.any? %>
  <div class="field">
    <%= user_group_select_field form, :user_group_id %>
  </div>
<% end %>

<% if component_settings.attachments_allowed? && @proposal %>
  <fieldset class="gallery__container">
    <legend><%= t("gallery_legend", scope: "decidim.proposals.proposals.edit") %></legend>

    <% if @form.photos.any? %>
      <% @form.photos.each do |photo| %>
        <div class="callout gallery__item" id="attachment_<%= photo.id %>" data-closable>
          <%= image_tag photo.thumbnail_url, class: "thumbnail", alt: photo.file.filename %>
          <%= form.hidden_field :photos, multiple: true, value: photo.id, id: "photo-#{photo.id}" %>
          <button class="close-button"
                  aria-label="<%= t("delete_image", scope: "decidim.proposals.proposals.edit") %>"
                  title="<%= t("delete_image", scope: "decidim.proposals.proposals.edit") %>"
                  type="button"
                  data-close>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    <% end %>

    <div class="row column">
      <%= form.file_field :add_photos, multiple: false, label: t("add_images", scope: "decidim.proposals.proposals.edit") %>
    </div>
  </fieldset>

  <fieldset class="gallery__container">
    <legend><%= t("attachment_legend", scope: "decidim.proposals.proposals.edit") %></legend>

    <% if @form.documents.any? %>
      <% @form.documents.each do |document| %>
        <div class="callout" id="attachment_<%= document.id %>" data-closable>
          <%= link_to translated_attribute(document.title), document.url %>
          <small><%= document.file_type %> <%= number_to_human_size(document.file_size) %></small>
          <%= form.hidden_field :documents, multiple: true, value: document.id, id: "document-#{document.id}" %>
          <button class="close-button"
                  aria-label="<%= t("delete_document", scope: "decidim.proposals.proposals.edit") %>"
                  title="<%= t("delete_document", scope: "decidim.proposals.proposals.edit") %>"
                  type="button" data-close>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    <% end %>

    <div class="row column">
      <%= form.file_field :add_documents, multiple: true, label: t("add_documents", scope: "decidim.proposals.proposals.edit") %>
    </div>
  </fieldset>
<% end %>

<div class="field">
  <label>
    <%= check_box_tag "confirmation", "yes", false, required: true %>Confirmo
    haber leído el
    <%= link_to "catálogo de proyectos",
                "https://decidimos.monterrey.gob.mx/processes/presupuesto-participativo-2024/f/167/",
                target: "_blank",
                rel: "nofollow" %>
    y entiendo que para ser factible, mi propuesta debe obtener una factibilidad técnica, jurídica y presupuestal favorable por las dependencias municipales.
  </label>
</div>

app/views/decidim/proposals/proposals/_vote_button.html.erb
<% if proposal.rejected? || proposal.withdrawn? %>
  <div></div>
<% else %>
  <% if component_settings.participatory_texts_enabled? && from_proposals_list %>
    <%= render partial: "decidim/proposals/proposals/participatory_texts/proposal_vote_button", locals: { proposal: proposal, from_proposals_list: true } %>
  <% else %>
    <div id="proposal-<%= proposal.id %>-vote-button" class="button--vote-button">
      <% if !current_user %>
        <% if current_settings.votes_blocked? %>
          <%= action_authorized_button_to :vote, t("decidim.proposals.proposals.vote_button.votes_blocked"), proposal_proposal_vote_path(proposal_id: proposal, from_proposals_list: from_proposals_list), resource: proposal, class: "button #{vote_button_classes(from_proposals_list)} disabled", disabled: true %>
        <% else %>
          <%= action_authorized_button_to :vote, proposal_proposal_vote_path(proposal_id: proposal, from_proposals_list: from_proposals_list), resource: proposal, class: "button #{vote_button_classes(from_proposals_list)}", data: { disable: true, "redirect-url": proposal_path(proposal) } do %>
            <%= t("decidim.proposals.proposals.vote_button.vote") %>
            <span class="show-for-sr"><%= decidim_html_escape(present(proposal).title) %></span>
          <% end %>
        <% end %>
      <% else %>
        <% if @voted_proposals ? @voted_proposals.include?(proposal.id) : proposal.voted_by?(current_user) %>
          <%= action_authorized_button_to(
            :vote,
            proposal_proposal_vote_path(proposal_id: proposal, from_proposals_list: from_proposals_list),
            resource: proposal,
            method: :delete,
            remote: true,
            data: {
              disable: true,
              original: t("decidim.proposals.proposals.vote_button.already_voted"),
              replace: t("decidim.proposals.proposals.vote_button.already_voted_hover"),
              "redirect-url": proposal_path(proposal)
            },
            class: "button #{vote_button_classes(from_proposals_list)} active light",
            id: "vote_button-#{proposal.id}"
          ) do %>
            <%= icon("check", class: "icon--small") %>
            <%= t("decidim.proposals.proposals.vote_button.already_voted") %>
            <span class="show-for-sr"><%= decidim_html_escape(present(proposal).title) %></span>
          <% end %>
        <% else %>
          <% if proposal.maximum_votes_reached? && !proposal.can_accumulate_supports_beyond_threshold && current_component.participatory_space.can_participate?(current_user) %>
            <%= content_tag :button, t("decidim.proposals.proposals.vote_button.maximum_votes_reached"), class: "button #{vote_button_classes(from_proposals_list)} disabled", disabled: true %>
          <% else %>
            <% if vote_limit_enabled? && remaining_votes_count_for(current_user) == 0 %>
              <%= content_tag :button, t("decidim.proposals.proposals.vote_button.no_votes_remaining"), class: "button #{vote_button_classes(from_proposals_list)}", disabled: true %>
            <% elsif current_settings.votes_blocked? || !current_component.participatory_space.can_participate?(current_user) %>
              <%= content_tag :button, t("decidim.proposals.proposals.vote_button.votes_blocked"), class: "button #{vote_button_classes(from_proposals_list)} disabled", disabled: true %>
            <% elsif current_component.scope.present? && is_component_scope_district?(current_component) && !user_can_vote_district_proposal?(current_user, proposal) %>
              <%= content_tag :button, t("decidim.proposals.proposals.vote_button.out_of_scope.district"), class: "button #{vote_button_classes(from_proposals_list)} disabled", disabled: true %>
            <% elsif current_component.scope.present? && is_component_scope_sector?(current_component) && !user_can_vote_sector_proposal?(current_user, proposal) %>
              <%= content_tag :button, t("decidim.proposals.proposals.vote_button.out_of_scope.sector"), class: "button #{vote_button_classes(from_proposals_list)} disabled", disabled: true %>
            <% else %>
              <%= action_authorized_button_to :vote, proposal_proposal_vote_path(proposal_id: proposal, from_proposals_list: from_proposals_list), resource: proposal, remote: true, data: { disable: true, "redirect-url": proposal_path(proposal) }, class: "button #{vote_button_classes(from_proposals_list)}" do %>
                <%= t("decidim.proposals.proposals.vote_button.vote") %>
                <span class="show-for-sr"><%= decidim_html_escape(present(proposal).title) %></span>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/decidim/proposals/proposals/_voting_rules.html.erb
<% if show_voting_rules? %>
  <div class="row column voting-rules">
    <div class="callout secondary">
      <div class="row">
        <div class="columns medium-8 large-9">
          <h3 class="heading3"><%= t(".title") %></h3>
          <ul>
            <% if vote_limit_enabled? %>
              <li><%= t(".vote_limit.description", limit: component_settings.vote_limit) %></li>
            <% end %>
            <% if proposal_limit_enabled? %>
              <li><%= t(".proposal_limit.description", limit: proposal_limit) %></li>
            <% end %>
            <% if threshold_per_proposal_enabled? %>
              <li><%= t(".threshold_per_proposal.description", limit: threshold_per_proposal) %></li>
            <% end %>
            <% if can_accumulate_supports_beyond_threshold? %>
              <li><%= t(".can_accumulate_supports_beyond_threshold.description", limit: threshold_per_proposal) %></li>
            <% end %>
            <% if minimum_votes_per_user_enabled? %>
              <li>
                <%= t(".minimum_votes_per_user.description", votes: minimum_votes_per_user) %>
                <% if votes_given >= minimum_votes_per_user %>
                  <%= t(".minimum_votes_per_user.given_enough_votes") %>
                <% else %>
                  <%= t(".minimum_votes_per_user.supports_remaining", remaining_votes: minimum_votes_per_user - votes_given) %>
                <% end %>
              </li>
            <% end %>
            <% if current_user && component_settings.scopes_enabled %>
              <li><%= raw t(get_proposals_component_scope_vote_message_key(component_settings), scope_name: user_scope_name(current_user, component_settings)[I18n.locale.to_s]) %></li>
            <% end %>
          </ul>
        </div>
        <% if current_user_can_vote? %>
          <div class="columns medium-4 large-3">
            <div class="card card--nomargin text-center remaining-votes-counter">
              <div class="card__content">
                <span class="definition-data__title"><%= t(".vote_limit.left", limit: component_settings.vote_limit) %></span>
                <%= render partial: "decidim/proposals/proposals/remaining_votes_count" %>
                <span class="extra__suport-text"><%= t(".vote_limit.votes") %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/decidim/proposals/proposals/_wizard_header.html.erb
<% if @step == :step_4 %>
    <% body_messages = [t("decidim.proposals.proposals.preview.announcement_body")]
    if component_settings.proposal_edit_time == "limited"
      days_minutes = component_settings.proposal_edit_before_minutes.divmod(24 * 60)
      days = days_minutes[0]
      hours_minutes = component_settings.proposal_edit_before_minutes.divmod(60)
      hours = hours_minutes[0]
      if (days > 0)
        hours = days_minutes[1].divmod(60)[0]
        body_messages << t("decidim.proposals.proposals.preview.proposal_edit_before_minutes.days", days: days, hours: hours)
      elsif (hours > 0)
        minutes = hours_minutes[1]
        body_messages << t("decidim.proposals.proposals.preview.proposal_edit_before_minutes.hours", hours: hours, minutes: minutes)
      else
        body_messages << t("decidim.proposals.proposals.preview.proposal_edit_before_minutes", count: component_settings.proposal_edit_before_minutes)
      end
    end %>

  <%= cell(
    "decidim/announcement",
    {
      title: t("decidim.proposals.proposals.preview.announcement_title"),
      body: body_messages
    },
    callout_class: "warning"
  ) %>
<% else %>
  <%= cell("decidim/announcement", component_settings.new_proposal_help_text) %>
<% end %>

<% if proposal_wizard_step_help_text?(@step) %>
  <div class="proposal_wizard_help_text">
    <% callout_step_help_text_class ||= nil %>
    <%= cell(
      "decidim/announcement",
      component_settings.try("proposal_wizard_#{@step}_help_text"),
      callout_class: callout_step_help_text_class
    ) %>
  </div>
<% end %>

<h2 class="section-heading">
  <%= proposal_wizard_step_title action_name %>
  <%= "(#{@similar_proposals.count})" if @similar_proposals.present? %>
</h2>

<div class="hide-for-large m-bottom">
  <div><%= proposal_wizard_steps_title %></div>
  <div><%= proposal_wizard_current_step_of(@step) %></div>

  <div id="steps" class="wizard__steps steps-toggle is-hidden" data-toggler=".is-hidden">
    <%= proposal_wizard_stepper(@step) %>
  </div>
</div>

app/views/decidim/proposals/proposals/index.html.erb
<%= render partial: "decidim/shared/component_announcement" %>

<% if component_settings.geocoding_enabled? %>
  <%= dynamic_map_for proposals_data_for_map(@all_geocoded_proposals) do %>
    <template id="marker-popup">
      <div class="map-info__content">
        <h3>${title}</h3>
        <div id="bodyContent">
          <p>{{html body}}</p>
          <div class="map__date-address">
            <div class="address card__extra">
              <div class="address__icon">{{html icon}}</div>
              <div class="address__details">
                <span>${address}</span><br>
              </div>
            </div>
          </div>
          <div class="map-info__button">
            <a href="${link}" class="button button--sc">
              <%= t(".view_proposal") %>
            </a>
          </div>
        </div>
      </div>
    </template>
  <% end %>
<% end %>
<%= render partial: "create_proposal_rules" if current_user && proposal_limit_enabled? %>
<%= render partial: "voting_rules" %>
<div class="row columns">
  <div class="title-action">
    <h3 id="proposals-count" class="title-action__title section-heading">
      <%= render partial: "count" %>
    </h3>
    <% if current_settings.creation_enabled && current_component.participatory_space.can_participate?(current_user) %>
      <%= action_authorized_link_to :create, new_proposal_path, class: "title-action__action button small", data: { "redirect_url" => new_proposal_path } do %>
        <%= t(".new_proposal") %>
        <%= icon "plus", role: "img", "aria-hidden": true %>
      <% end %>
    <% end %>

    <% if component_settings.collaborative_drafts_enabled? %>
      <%= link_to t(".collaborative_drafts_list"), collaborative_drafts_path, class: "title-action__action button small hollow ml-s" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="columns mediumlarge-4 large-3">
    <%= render partial: "filters_small_view" %>
    <div class="card card--secondary show-for-mediumlarge">
      <%= render partial: "filters" %>
    </div>
  </div>
  <div id="proposals" class="columns mediumlarge-8 large-9" aria-live="polite">
    <%= render partial: "proposals" %>
  </div>
</div>
<div class="row">
  <div class="text-right">
    <%= link_to t(".see_all_withdrawn"), proposals_path("filter[state][]" => "withdrawn") %>
  </div>
</div>

<%# Fragmento sacado de app/views/decidim/proposals/proposals_votes/update_buttons_and_counters.js.erb %>
<script>
window.onload = function() {
  <% @proposals.each do |proposal| %>
    var $proposalVoteButton = $('#proposal-<%= proposal.id %>-vote-button');
    if($proposalVoteButton[0]) {
      morphdom($proposalVoteButton[0], '<%= j(render partial: "decidim/proposals/proposals/vote_button", locals: { proposal: proposal, from_proposals_list: true }).strip.html_safe %>');
    }
  <% end %>
};
</script>

app/views/decidim/proposals/proposals/index.js.erb
var $proposals = $('#proposals');
var $proposalsCount = $('#proposals-count');
var $orderFilterInput = $('.order_filter');

$proposals.html('<%= j(render partial: "proposals").strip.html_safe %>');
$proposalsCount.html('<%= j(render partial: "count").strip.html_safe %>');
$orderFilterInput.val('<%= order %>');

var $dropdownMenu = $('.dropdown.menu', $proposals);
$dropdownMenu.foundation();